### ISSUE TITLE
New backend using io_uring

### ISSUE THREAD

**Issue by ng5** [uNetworking/uSockets#129]
io_uring - New asynchronous IO eventing added since linux kernel 5.1. Could be a possible enhancement given uSockets has already abstracted event polling backends.

Some performance benchmarks compared to epoll
Provided by GitHub user https://github.com/frevib

https://github.com/frevib/io_uring-echo-server/blob/io-uring-op-provide-buffers/benchmarks/benchmarks.md

**Comment by alexhultman** [comment]
I am aware of that. Frevib's benchmarks are not credible at the moment though. I'm still waiting for anyone to outperform epoll with a test that is reproducible.

**Comment by alexhultman** [comment]
https://github.com/frevib/io_uring-echo-server/issues/8

**Comment by mohsenomidi** [comment]
it is awesome to add the io_uring mechanism to the library to support high performance networking 

 [IO_uring vs epoll echo server; +99% performance, -45% CPU usage](https://www.reddit.com/r/C_Programming/comments/eqwl2d/io_uring_vs_epoll_echo_server_99_performance_45/)

**Comment by alexhultman** [comment]
@mohsenomidi please use your eyeballs to read your own links before you blindly repost them here. Your link is clearly nonsense, it even states that itself. Can we please start using our brains and eyeballs here?

**Comment by mohsenomidi** [comment]
@alexhultman 

Hi man, 
Hope you are doing well...

I can not understand your angry response for my post, even if I made some duplicate or wrong post !
My apologize, about what you think and the things that make you angry.I always respect to the people and they words, anyway, about the link I provided here, is the same link in your commented link reference here on this (the tweet of same reporter) [comment](https://github.com/frevib/io_uring-echo-server/issues/8#issuecomment-683422030), I just did not read that post in that repository. 
About IO_URING there are many articles and implementations to prove how we can get great performance than epoll. 
That library (frevib/io_uring-echo-server) is only an example and may buggy. I prefer to skip this now. 

Good Luck :-)

**Comment by alexhultman** [comment]
This is scathing criticism, not anger. They are two entirely different things. One is a _feeling_ another is a logical response to moronic behavior.

**Comment by alexhultman** [comment]
It is said Linux 5.11 will have optimizations to io_uring so rerunning beckmans then can be a good idea.

**Comment by alexhultman** [comment]
There are many disadvantages to io_uring, esp. when dealing with tons of mostly-idle connections like with websockets. It's the same disadvantages as Windows IOCP has - mainly that you have to bind tons of user space memory to something that may happen in the future. This has massive disadvantages to memory usage and goes against much of what the point of uWS is. Further on the supposed performance improvements have been very mild, if none at all.

IO_uring should still be experimented with and assessed, but it should not be added just because of the hype. It should only be added if a significant, scientific gain can be shown (this, I'm still waiting for). We don't do things out of hype here - this is why we skip things that are hyped like sendfile and writev when the gains are impractical or none, for the core use cases.

Nobody has really presented anything that can outperform uWS either way, so we don't really need to respond to hype just because it is hyped. I don't care about new things unless there is real, scientific gain that significantly outweighs the disadvantages.

**Comment by alexhultman** [comment]
It can also be said that we kind of already do support IO_uring since we support libuv - maybe not an ideal support but we definitely do support it (can always be improved, but still).

**Comment by alexhultman** [comment]
io_uring is slower than epoll.

**Comment by LifeIsStrange** [comment]
@alexhultman you should reconsider, as you know from the latests comment of your own issue on liburing, on kernel 5.12 (and even 5.11?) the performance is better vs plain epoll, even with mitigations=off

**Comment by alexhultman** [comment]
I first need a benchmark that shows a significant gain *on my computer* otherwise it is impossible for me to develop for this API. I need to be able to benchmark as I go to know if I am doing it correctly, can't just develop and hope it will run fast when done.
