### ISSUE TITLE
QUIC

### ISSUE THREAD

**Issue by alexhultman-2fa** [uNetworking/uSockets#134]
We have to add support for at least one QUIC-stack to allow uWS to support QuicTransport whenever it launches.

LightSpeed's QUICK-stack looks like a promising start - it is entirely C

**Comment by alexhultman** [comment]
While adding QUIC - benchmarking must be done throughout. Because we know the speed of TLS/TCP and can measure it with tools made here - we should expect the same performance using QUIC when done. If performance is less than what we already have with TLS/TCP then the implementation of UDP/QUIC is wrong and needs to be thrown out.

If we can get the same performance; good - then we are on the right track. Of course, slight deviations can occur because it is not the exact same algorithms used, but performance should really be roughly the same.

We already have SSL/non-SSL as an integer to all socket functions. This should now be extended to have 3 "protocols": TCP = 0, TLS = 1 and QUIC = 2. So you still have the same interface (with a few functions added of course) for all three "transports".

New features of QUIC should be added for all transports, and ignored for those who don't implement it. So the uSockets interface should be the same for all three.

**Comment by alexhultman** [comment]
QUIC actually do use TLS1.3, the same as is used over TCP - so requiring the same performance really has to be a strict goal! It MUST perform the same!

**Comment by zmajeed** [comment]
What about Microsoft's MsQuic? https://github.com/microsoft/msquic - also all C - looks simpler to use https://github.com/microsoft/msquic/blob/main/docs/API.md

**Comment by alexhultman** [comment]
I've been developing C++ on Microsoft platforms and tools since 1998 and from my experience Microsoft never understood what C++ was about, or how to make the developer experience somewhat nice, or taste in general. So even if they (might) have a nice stack I would try and stay as far away as possible - but never say never I will do benchmarking and select whatever works the best. But my guy feeling so far leans towards lsquic

**Comment by zmajeed** [comment]
I just came across it today looking for C or C++ QUIC libraries - your interest too popped up so I figured if you're gonna look at something ...

**Comment by nibanks** [comment]
In defense of MsQuic, we are 100% C because it has to run in the Windows kernel, which doesn't support many C++ features sadly (no std lib; no exceptions). 
We have started building a C++ wrapper to our API (msquic.hpp) for user mode but is mostly just a WIP. We'd be happy to accept any PRs that could improve it. If you have any problems with the API, even if you don't end up using it, feel free to open an issue on our repo!

On the topic of performance, that's one of our primary goals with MsQuic, and as far as we've testing MsQuic generally has the best performance around. Here's our dashboard if you're interested: https://microsoft.github.io/msquic/index.html.

**Comment by alexhultman-2fa** [comment]
I guess my point is that, unless there is very obvious incentives to go with Microsoft's implementation, I rather not (becaue of history such as Internet Explorer and Visual C++ and Win32). But if it turns out that MsQuic does things that no other implementation can do - then sure I can consider it. I still haven't started benchmarking different stacks, so I cannot say anything about it yet. lsquic looks nice and is supported by a big company - if their stack performs like I hope it does then I don't see why I should use something else

**Comment by nibanks** [comment]
Sad to see you went with lsquic instead of msquic. MsQuic is the fastest QUIC implementation available, from the last time we did cross-implementation testing; and we are constantly working on improving the perf for MsQuic even more. Let me know if you like to try out msquic in the future, to see how it compares. Good luck!

**Comment by alexhultman** [comment]
I'm 110% certain I can beat MsQuic with lsquic since I know for a fact BoringSSL outperforms OpenSSL for short messages by 18% and MsQuic seems to use an off-brand fork of OpenSSL that hasn't been updated since Obama was president - so already from the start it's entirely improbable MsQuic would be any good on Linux. Besides, I have benchmarked lsquic and it has excellent performance that matches the TLS performance almost identically - which is a really good sign since we have tons of benchmarks with TLS. So we are all good here

**Comment by nibanks** [comment]
> I'm 110% certain I can beat MsQuic with lsquic

If you're able to do that, **please** open a bug on MsQuic! Thanks!

**Comment by alexhultman** [comment]
It's not a property of MsQuic or lsquic it's a property of OpenSSL vs. BoringSSL. I know very well that BoringSSL significantly outperforms OpenSSL on short messages, last benchmark put the difference at 18%. So anything that relies on OpenSSL is a no no, and especially something that relies on a fork that hasn't been updated at all.

**Comment by alexhultman** [comment]
BoringSSL is faster than OpenSSL for small messages while OpenSSL is faster at large ones. Most messages are small when doing WebSockets and such eventing so BoringSSL is definitely preferable.

![image](https://user-images.githubusercontent.com/3397140/149991860-199ef93a-8c36-477b-ac42-477f2f0fc62f.png)

**Comment by nibanks** [comment]
Is "message length" here is the TLS message layer?

**Comment by alexhultman** [comment]
Not sure, all I know is BoringSSL is way faster than OpenSSL in my tests and that's why I prefer it. But don't worry, I will make a buttload of benchmarks of this when it is done. lsquic also comes with built-in http3 support, btw.

**Comment by nibanks** [comment]
> But don't worry, I will make a buttload of benchmarks of this when it is done

Thanks! I am very interested in the results. If you want help throwing together branch with a minimal version using MsQuic, just to compare please let me know.

> lsquic also comes with built-in http3 support, btw.

Is that a goal/requirement for this project?
