### ISSUE TITLE
doesn't build on ubuntu 18.04 LLVMgold.so missing

### ISSUE THREAD

**Issue by vird** [uNetworking/uSockets#16]
In fact sorry about posting here, but uWebSockets doesn't accept issues.
preparations

    # make new machine on cloud hetzner
    mkdir uws
    cd uws
    git clone https://github.com/uNetworking/uWebSockets --recursive
    apt install -y make clang libssl-dev
    cd uWebSockets
    make

output

    clang -flto -O3 -c -IuSockets/src uSockets/src/*.c uSockets/src/eventing/*.c
    clang++ -flto -O3 -c -std=c++17 -Isrc -IuSockets/src examples/HelloWorld.cpp
    clang++ -flto -O3 -s *.o -o HelloWorld
    /usr/bin/ld: /usr/lib/llvm-6.0/bin/../lib/LLVMgold.so: error loading plugin: /usr/lib/llvm-6.0/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Makefile:4: recipe for target 'examples' failed
    make: *** [examples] Error 1

`apt install -y llvm` doesn't help

clang -v

    clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
    Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
    Candidate multilib: .;@m64
    Selected multilib: .;@m64

**Comment by alexhultman** [comment]
Please do not open issues regarding other projects. Also, do not report build errors, they are almost entirely caused by user error or third party errors. 95 out of 100 bug reports are build issues, I don't take them.

I don't know what your particular issue is about, but I know how to use Google and I found this: https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-snapshot/+bug/1254970

Next time please Google yourself, your compiler clearly stated a perfectly Google-able line.
