### ISSUE TITLE
Zig experiment ?

### ISSUE THREAD

**Issue by e3dio** [uNetworking/uSockets#199]
Rust is safe, but Zig is more fun, maybe try both and see how it goes?

[When Zig is safer and faster than Rust](https://zackoverflow.dev/writing/unsafe-rust-vs-zig/)
https://news.ycombinator.com/item?id=35058176

**Comment by uNetworkingAB** [comment]
Yeah this is kind of similar to what I've been thinking of myself - unsafe Rust is not better than C, in fact it's worse since you don't have **official** system APIs but have to depend on **highly out of sync, hacky, third-party** "crates" that promise to wrap the system properly (hint: it doesn't). And everything still has to be unsafe so there is no point in moving from C, esp. not if Rust has these messed up UB rules.

The only place where Rust can be better is where **everything can be safe**, such as when making **abstract apps**. There it can excel because business logic is often **riddled with bugs**. But there is hype around Rust, esp. in finance where governmental regulation press on not using C/C++ in financial apps so if anything it has to be Rust, not Zig. But it will probably stay C because it makes no sense to move away from official system APIs.
