### ISSUE TITLE
External Endpoint

### ISSUE THREAD

**Issue by Drog-ahrk-In** [uNetworking/uSockets#68]
As far as I have done my research it is not possible to create a connection to another server architecture type (Client support)? For example connecting to a Node HTTP server and sending custom headers? Just clearing doubts here. I know that uWebSockets has this type of functionality, but I prefer C over C++.

**Comment by JadeVand** [comment]
In context.c there is a function `struct us_socket_t *us_socket_context_connect(int ssl, struct us_socket_context_t *context, const char *host, int port, int options, int socket_ext_size)` which I can only assume is used to connect to an external endpoint. Since it returns a `us_socket_t` structure you could use that to read and write from the remote endpoint.

**Comment by alexhultman** [comment]
You can connect yes, there are examples in examples folder.
